"""Offline email signal contract. Stops at a canonical trade instruction."""

from swingtrade.group4_email.contract import (
    CALENDAR_ASSUMPTION,
    EMAIL_RETENTION_POLICY,
    EXIT_ALERT_PARSER,
    FIXTURE_SIGNAL_MAILBOX,
    PARSER_VERSION,
    QUANTITY_ROUNDING_POLICY,
    SCHEMA_VERSION,
    SIGNAL_MAILBOX,
    TIMEZONE_ASSUMPTION,
    TRADE_AMENDMENT_PARSER,
    TRADE_CANCEL_PARSER,
    CanonicalInstructionEnvelope,
    Direction,
    Disposition,
    ExitAlertInstruction,
    MessageType,
    NewTradeInstruction,
    OrderType,
    ParseOutcome,
    ParseProvenance,
    ProviderType,
    SessionEvent,
    SiblingCancel,
    TimeInForce,
    TradeAmendmentInstruction,
    TradeCancelInstruction,
    TriggerBasis,
)
from swingtrade.group4_email.extract import economic_decimal
from swingtrade.group4_email.parse import MessageIdentityRegistry, parse_email

__all__ = [
    "CALENDAR_ASSUMPTION",
    "EMAIL_RETENTION_POLICY",
    "EXIT_ALERT_PARSER",
    "FIXTURE_SIGNAL_MAILBOX",
    "PARSER_VERSION",
    "QUANTITY_ROUNDING_POLICY",
    "SCHEMA_VERSION",
    "SIGNAL_MAILBOX",
    "TIMEZONE_ASSUMPTION",
    "TRADE_AMENDMENT_PARSER",
    "TRADE_CANCEL_PARSER",
    "CanonicalInstructionEnvelope",
    "Direction",
    "Disposition",
    "ExitAlertInstruction",
    "MessageIdentityRegistry",
    "MessageType",
    "NewTradeInstruction",
    "OrderType",
    "ParseOutcome",
    "ParseProvenance",
    "ProviderType",
    "SessionEvent",
    "SiblingCancel",
    "TimeInForce",
    "TradeAmendmentInstruction",
    "TradeCancelInstruction",
    "TriggerBasis",
    "economic_decimal",
    "parse_email",
]
